### ISSUE TITLE
register_with_elb.sh on asg with spot instances fails to transition from standby to in service

### ISSUE THREAD

**Issue by chriskinsman** [awslabs/aws-codedeploy-samples#30]
It appears to get stuck on a waiting for lifecycle action step.

It is almost as through transitioning the spot instance to standby causes a new ec2_instance_launching lifecycle transition and then it gets stuck waiting for another deployment hook

I have one instance where this works and another where it doesn't and ultimately the lifecycle hook times out the instance is terminated and a new instance is spun up.

Found more about this.  Looks like a spot instance transitions through EC2_INSTANCE_LAUNCHING when moving from Standby to InService which causes all deployments targeting it to run again as though it was just created.  Including the currently running deployment!  It never finishes as you might imagine due to this recursion...

Dropping a spot instance to standby in the console and then putting it back in service works fine but unclear what console is doing...

Very weird...

**Comment by yubangxi** [comment]
Hi,

The issue was that lifecycle hooks were applied to spot instances when they were attached to an Auto Scaling Group or when they were exiting Standby. That was incorrect behavior as lifecycle hooks should only be applied to newly launched instances. The fix for this issue has been deployed to all public regions as of Nov 3.
