### ISSUE TITLE
deregister_from_elb.sh does not wait for de-registration from specified Target Groups

### ISSUE THREAD

**Issue by abhimanyu1289** [awslabs/aws-codedeploy-samples#64]
Due to `exit 0`   in deregister_from_elb.sh script(line 47)  does not wait or try to de-register from target groups if an instances is also part of an Auto Scaling group

**Comment by schmohlio** [comment]
bumping. any reason the script exits here?

**Comment by mmerkes** [comment]
From what I can see, it looks like if the script sees that the host is port of an ASG, it tries to put that host into standby. If AutoScaling knows that it's associated with an ELB (i.e. you configured your ASG to be so via AutoScaling), AutoScaling will try to deregister the host with the ELB as part of the process of going into standby. Thus, the script doesn't need to interact with ELB in that case, and it exits because mission accomplished. It only has to de-register directly (and get past this line) if the host is not an ASG host.

However, if you register your ASG hosts with the ELB directly and not via AutoScaling, AutoScaling does not know that there is an ELB associated with it and will not try to deregister the host from the ALB. Is this the scenario you're describing? @abhimanyu1289 

IMO, the best fix is to associate all ASGs with their ELBs via AutoScaling properties, which should have the expected behavior. Alternatively, we could check in the script if it's an ASG host and see if an ELB is associated with it; otherwise, it falls through to the rest of the script to handle de-registering directly, but I would rather rely on AutoScaling to de-register my hosts than a shell script.

**Comment by abhimanyu1289** [comment]
I agree. Thanks for the explanation.
