### ISSUE TITLE
elb-v2 scripts stopped working

### ISSUE THREAD

**Issue by mhemmings** [awslabs/aws-codedeploy-samples#68]
I've had the elb-v2 working brilliantly in production for months, and all of a sudden this week deploys no longer succeed.

They fail on `Application Stop` with the following logs:

```
...
[stderr]Instance is currently in state: EnteringStandby
[stderr]Instance is currently in state: EnteringStandby
[stderr]Instance is currently in state: EnteringStandby
[stderr]Instance failed to reach state, Standby within 60 seconds
```

**Comment by schmohlio** [comment]
The same happened with me starting last week. Turns out deregistering from the load balancer (calling AWS endpoint) is taking way longer. I had to bump up my wait time on the `Application Stop` scripts. 

You will probably notice that the first time you change your `Application Stop` scripts you need to enable `don't fail on application stop`. While this is a serious annoyance, you sould probably design your app_spec scripts to be idempotent, so that you can ignore errors on application stop.

**Comment by jweberst** [comment]
This happened to us as well. After some research, I BELIEVE this is what happened, but I cannot know for certain.

Currently, when you do a deployment, deregister_elb.sh first removes the instance from the ASG, then from the ELB. When it removes the instance from the ASG, it runs a wait_for_state for Standby. However, now, it is taking a very large amount of time to leave the EnterStandby state and go into Standby.

I watched a deployment, the state on the ASG after it put it into standby was "Waiting for ELB Connection Draining." If this is the default for the ALB of 300 seconds, this will be 300 seconds.

My theory is that, before last week, the ASG did not care about the ELB or wait for the connection draining when going into Standby. They were separate processes.

I never watched it this closely before, but it makes sense. If the connection draining was always done during the ASG Standby phase, the deregister_elb would not then have to deregister the instance from the ELB after removing it from the ASG, which it does.

To fix this on our end, we just reduced our connection draining time to around 30 seconds. 300 was extremely excessive for our applications, but we had just left default.

Anyway, that is my theory. I would love to hear an official response.

**Comment by schmohlio** [comment]
I received this response from AWS support. Surprised, considering there is a whole article about ASG + CodeDeploy support. The word "support" comes up in the article with regards to these scripts working for `OneAtATime`. Rather misleading...

```
Being an open source project, the scripts in the AWS CodeDeploy Samples repository are the result of a collaboration effort comprising the contribution of both customers and Amazon Web Services, therefore they can only be provided on an 'as is' basis; these scripts are meant to be used for general guidance, and to give practical examples on the capabilities of CodeDeploy, hence they are not intended to be used directly in production.```

**Comment by mmerkes** [comment]
I'm an engineer at AWS CodeDeploy, and we're looking into this. We know that customers depend on these scripts and will work to get them working as expected!

@schmohlio @jweberst @mhemmings If you could post any additional context here, it'd be greatly appreciated. i.e. Are you using ALB or ELB? Are you all using ASGs? Etc.

I will post any updates on the issue here.

**Comment by jweberst** [comment]
@mhemmings we are using ALBs with ASGs. I don't have any additional context beyond what I already stated. Basically, reducing the ALB connection draining timeout to 30 seconds fixed the issue for us. We had it at 300. That's why I assume its related to connection draining and the ASG.

I haven't tried making a stock setup that deploys a hello world application with all defaults and these scripts, but I do believe one would not work. The items that we have modified in the script aren't related to this level of the functionality.

**Comment by schmohlio** [comment]
@mmerkes Hi Matt, thanks for your help. We are using ALBs + ASG as well. I don't really see this issue as a bug, since one can just decrease the connection draining or increase their timeout on app_spec.yml . That having been said, not sure why it changed. Also, not sure why ALB doesn't have a HANDLE_PROCS function to disable auto scaling. We currently don't have a scaling policy setup in our ASG.

In general, it'd be great if this sort of 1) de-registration and 2) disabling of ASG actions that will render incorrect deployment results be supported by CodeDeploy as a service. 

Because this doesn't quite feel production ready, we are running out app across 2 regions, and using Route53 to swap in our staging and prod environments. In dev and QA we are using OneAtATime deploy to a single region.

**Comment by mmerkes** [comment]
I reproduced the issue with a hello world app and the scripts in this projects, and it's just as you say @jweberst If you have an ASG with an ALB associated with it, the script will fail as is. I confirmed with AutoScaling that they recently released a change to respect ALB's connection draining/deregistration delay setting for target group. The default is 300 seconds, so it obviously times out with the current 180 second timeout.

As mentioned above, to fix the issue, you can either decrease the connection draining timeout in the ALB or increase the ASG wait time inside the script. I'm going to create a PR to make the script work out of the box.

@schmohlio We do offer [some ELB integration directly with CodeDeploy](http://docs.aws.amazon.com/codedeploy/latest/userguide/integrations-aws-elastic-load-balancing.html). Unfortunately, we don't currently support ALB directly with CodeDeploy, but we know our customers would love to see it. We do have ELB integration with the classic ELB, and we do blue/green deployments, which is very similar to what you describe with swapping environments.

**Comment by jweberst** [comment]
@mmerkes that's good to hear, thanks for fixing it.

I would be interested to know why they stopped working and what changed. Clearly something had to have changed last week in either the Auto Scaling service or ELB Service. However, the release notes for all projects here: https://aws.amazon.com/releasenotes/ don't show anything of any note related to any of those systems in the past month.

**Comment by mmerkes** [comment]
@jweberst I don't know the details, but the change was in AutoScaling. When you put a host into standby, they now honor the connection draining timeout in ELB. I wouldn't be surprised if it wasn't in the release notes because it's mostly a bug fix, IMO. Thanks for identifying the problem. It made my job easy :)

**Comment by jweberst** [comment]
@mmerkes that makes sense. Thanks!
