### ISSUE TITLE
Code Deploy Edge Case with 1 ASG In Service server

### ISSUE THREAD

**Issue by resteinbock** [awslabs/aws-codedeploy-samples#9]
@geisbruch @Jmcfar @mpantelimon

There is an undesirable edge case that occurs when a Code Deploy revision is deployed to an ASG where there is only 1 "In-Service" server:

aws-codedeploy-samples/load-balancing/elb/common_functions.sh autoscaling_enter_standby() will cause the ASG minimum and desired number of servers to drop from 1 to 0 while the new revision is being deployed. This will cause the ASG to terminate the instance after the deployment is completed. You will then be left with no servers "In-Service" for your application.

For a "no-loss-time" deployment, the desired and minimum servers for the ASG should be incremented if the ASG maximum is high enough before taking a server offline to deploy a new revision.

**Comment by suryanarayanan** [comment]
Tracking this issue in https://forums.aws.amazon.com/thread.jspa?threadID=169858&tstart=0

**Comment by nemo** [comment]
#19 and this are duplicates.

**Comment by suryanarayanan** [comment]
This is fixed in https://github.com/awslabs/aws-codedeploy-samples/commit/e1e1501dc44084d6e7c0857ee84279061db73e80

**Comment by tylerbenson** [comment]
@suryanarayanan I don't think this problem was actually solved in e1e1501.  The script never tries to increase the desired (or minimum for that matter) instance count before setting the instance to standby.  Not to mention, the script never waits for the new instance to reach a healthy state.  I really think these things should be taken care of by either CodeDeploy or AutoScaling as it requires a lot more work otherwise.
